import React from 'react';
import { ResumeMatchResponse, ParseResumeResponse } from '../services/api';

interface Props {
  matchData: ResumeMatchResponse;
  parseData: ParseResumeResponse;
}

const AnalysisReportPrint: React.FC<Props> = ({ matchData, parseData }) => {
  return (
    <div id="printable-report" className="hidden print:block p-8 bg-white text-slate-900 font-sans">
      {/* Report Header */}
      <div className="border-b border-slate-200 pb-6 mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">AI Resume Analysis Report</h1>
          <p className="text-sm text-slate-500 mt-1">Generated by ResumeAI • {new Date().toLocaleDateString()}</p>
        </div>
        <div className="text-right">
          <div className="text-3xl font-extrabold text-indigo-600">{Math.round(matchData.ats_score)}/100</div>
          <div className="text-xs font-semibold text-slate-600 uppercase tracking-wider">{matchData.rating}</div>
        </div>
      </div>

      {/* File Meta */}
      <div className="grid grid-cols-3 gap-4 mb-6 p-4 bg-slate-50 rounded-lg text-sm">
        <div>
          <span className="text-slate-500 block text-xs">Filename</span>
          <span className="font-medium text-slate-800">{parseData.filename}</span>
        </div>
        <div>
          <span className="text-slate-500 block text-xs">Page Count</span>
          <span className="font-medium text-slate-800">{parseData.page_count} Page(s)</span>
        </div>
        <div>
          <span className="text-slate-500 block text-xs">Word Count</span>
          <span className="font-medium text-slate-800">{parseData.statistics.word_count} Words</span>
        </div>
      </div>

      {/* Score Breakdown */}
      <div className="mb-6">
        <h2 className="text-base font-bold text-slate-900 mb-3 border-b pb-1">Score Components</h2>
        <div className="grid grid-cols-3 gap-4 text-center">
          <div className="p-3 bg-emerald-50 rounded-lg">
            <span className="block text-xl font-bold text-emerald-700">{Math.round(matchData.skill_match_score)}%</span>
            <span className="text-xs text-emerald-800">Skill Match (45%)</span>
          </div>
          <div className="p-3 bg-indigo-50 rounded-lg">
            <span className="block text-xl font-bold text-indigo-700">{Math.round(matchData.vector_similarity_score)}%</span>
            <span className="text-xs text-indigo-800">Vector Similarity (35%)</span>
          </div>
          <div className="p-3 bg-purple-50 rounded-lg">
            <span className="block text-xl font-bold text-purple-700">{Math.round(matchData.section_completeness_score)}%</span>
            <span className="text-xs text-purple-800">Section Completeness (20%)</span>
          </div>
        </div>
      </div>

      {/* Skills Comparison */}
      <div className="grid grid-cols-2 gap-6 mb-6">
        <div>
          <h3 className="text-sm font-bold text-slate-900 mb-2">Matched Skills ({matchData.matched_skills.length})</h3>
          <div className="flex flex-wrap gap-1.5">
            {matchData.matched_skills.map((s) => (
              <span key={s} className="px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded text-xs">✓ {s}</span>
            ))}
          </div>
        </div>
        <div>
          <h3 className="text-sm font-bold text-slate-900 mb-2">Missing Skills ({matchData.missing_skills.length})</h3>
          <div className="flex flex-wrap gap-1.5">
            {matchData.missing_skills.map((s) => (
              <span key={s} className="px-2 py-0.5 bg-red-100 text-red-800 rounded text-xs">+ {s}</span>
            ))}
          </div>
        </div>
      </div>

      {/* Suggestions */}
      <div className="mb-6">
        <h3 className="text-sm font-bold text-slate-900 mb-2 border-b pb-1">AI Improvement Suggestions</h3>
        <ol className="list-decimal list-inside space-y-1 text-xs text-slate-700">
          {matchData.improvement_suggestions.map((item, idx) => (
            <li key={idx} className="leading-relaxed">{item}</li>
          ))}
        </ol>
      </div>

      {/* Footer */}
      <div className="text-center pt-4 border-t text-xs text-slate-400">
        AI Resume Analyzer • Placement Portfolio Project
      </div>
    </div>
  );
};

export default AnalysisReportPrint;
